version: '3.8'

services:

  db:
    build:
      context: ./BD-SOFT
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miguel
      POSTGRES_DB: Bd_Videojuego
    volumes:
      - BdData:/var/lib/postgresql/data
      - ./BD-SOFT/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./BACK-SOFT
    ports:
      - "7878:7878"
    depends_on:
      - db
    command: ["/usr/local/bin/wait-for-it.sh", "db:5432", "--", "node", "index.js"]

  frontend:
    build:
      context: ./FRONT-SOFT
    ports:
      - "5173:80"
    depends_on:
      - backend


volumes:
  BdData:
