name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Esto ejecutará el pipeline cuando se haga un push a la rama principal
  pull_request:
    branches:
      - main  # También se ejecutará en los PRs hacia la rama principal

jobs:
  # Job para construir y subir las imágenes Docker
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t miguely/arq-soft:bd-latest ./BD-SOFT
          docker build -t miguely/arq-soft:backend-latest ./BACK-SOFT
          docker build -t miguely/arq-soft:frontend-latest ./FRONT-SOFT

      - name: Push Docker images to Docker Hub
        run: |
          docker push miguely/arq-soft:db-latest
          docker push miguely/arq-soft:backend-latest
          docker push miguely/arq-soft:frontend-latest

  # Job para desplegar los contenedores en la red
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Docker Hub (for deployment)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Docker network if not exists
        run: docker network create conex || true

      - name: Deploy containers from Docker Hub images
        run: |
          docker run -d --name db --network conex -p 5432:5432 miguely/arq-soft:db-latest || { echo "Error deploying db"; exit 1; }
          docker run -d --name backend --network conex -p 7878:7878 miguely/arq-soft:backend-latest || { echo "Error deploying backend"; exit 1; }
          docker run -d --name frontend --network conex -p 5173:80 miguely/arq-soft:frontend-latest || { echo "Error deploying frontend"; exit 1; }

      - name: Notify deployment success
        run: echo "Deployment completed successfully!"
